-- Replace existing autocomplete history with curated articles from articles.txt

DELETE FROM items_history;

WITH curated_items(item_name) AS (
    VALUES
        ('Bananen'),
        ('Kiwi'),
        ('Trauben'),
        ('Äpfel'),
        ('Zitrone'),
        ('Mandarinen'),
        ('Orangen'),
        ('Zwiebeln'),
        ('Feldsalat'),
        ('Kopfsalat'),
        ('Salatgurke'),
        ('Tomaten'),
        ('Frühlingszwiebeln'),
        ('Karotten'),
        ('Knoblauch'),
        ('Kartoffeln'),
        ('Burger Buns'),
        ('Schwarzbrot'),
        ('Toastbrot'),
        ('Frischkäse'),
        ('Kräuterfrischkäse'),
        ('Naturjoghurt'),
        ('Mozarella'),
        ('Parmesan'),
        ('Reibekäse'),
        ('Milch'),
        ('Hackfleisch'),
        ('Würstchen'),
        ('Senf'),
        ('Ketchup'),
        ('Sonnenblumenöl'),
        ('Essig'),
        ('Balsamico'),
        ('Kalbfonds'),
        ('Lammfonds'),
        ('Currypaste'),
        ('Toilettenpapier'),
        ('Küchenpapier'),
        ('Mehl'),
        ('Zucker'),
        ('Dosentomaten'),
        ('Tomatenmark'),
        ('Bandnudeln'),
        ('Spaghetti'),
        ('Spätze'),
        ('Heidelbeeren aus dem Glas'),
        ('Kirschen aus dem Glas'),
        ('Dosenpfirsich'),
        ('Dosenananas'),
        ('Chips'),
        ('Rotbäckchensaft'),
        ('Pizza'),
        ('Eis'),
        ('Spinat')
)
INSERT INTO items_history (id, item_name, last_used_at)
SELECT lower(hex(randomblob(16))), item_name, datetime('now')
FROM curated_items;
